server:
  port: 8080

database:
  pg:
    host: "150.158.25.115"
    port: 5432
    username: "postgres"
    dbname: "shoe_shark"
    password: "1qazXSW@@"

logging:
  dir: './logs/'
  name: "shoe_shark"
  level: "info"
  max_size: 50
  enable: true
