app_mode: "dev"

server:
  port: 8080

database:
  pg:
    host: "xx"
    port: 5432
    username: "xx"
    dbname: "shoe_shark"
    password: "xxx"

eth:
  private_key: "xxx"
  fuji:
    url: "xxx"

logging:
  dir: './logs/'
  name: "shoe_shark"
  level: "debug"
  max_size: 50
  enable: true
