version: '3'
services:
  app:
    build:
      context: ../..  # 项目根目录作为构建上下文
      dockerfile: deployments/docker/Dockerfile  # 指定 Dockerfile 的路径
    image: shoe-shark-server:latest  # 指定镜像名称和标签
    container_name: shoe-shark-server
    ports:
      - "8080:8080"
    volumes:
      - ../../resources:/app/resources  # 挂载资源文件
      - ../../resources/static:/app/resources/static  # 挂载资源文件
    environment:
      - GIN_MODE=debug
    env_file:
      - /usr/shoe_shark/deploy_scripts/test.env
