basePath: /shoe-shark
definitions:
  req.CreateContentCommentReq:
    properties:
      contentId:
        type: string
      description:
        type: string
    type: object
  req.CreateContentReq:
    properties:
      description:
        type: string
      isPublic:
        type: boolean
      location:
        type: string
      title:
        type: string
    required:
    - description
    - title
    type: object
  req.UpdateContentReq:
    properties:
      contentId:
        type: string
      description:
        type: string
      isPublic:
        type: boolean
      location:
        type: string
      title:
        type: string
    required:
    - contentId
    - description
    - title
    type: object
  req.VerifySignatureReq:
    properties:
      accountAddress:
        type: string
      signature:
        type: string
    required:
    - accountAddress
    - signature
    type: object
  res.ContentInfoRes:
    properties:
      accountAddress:
        type: string
      contentID:
        type: string
      created_at:
        type: string
      description:
        type: string
      isPublic:
        type: boolean
      location:
        type: string
      title:
        type: string
    type: object
  res.CreateContentCommentRes:
    properties:
      accountAddress:
        type: string
      contentId:
        type: string
      createdAt:
        type: string
      description:
        type: string
    type: object
  res.GetNonceRes:
    properties:
      nonce:
        type: string
    type: object
  res.PointsLogRes:
    properties:
      createdAt:
        type: string
      isSyncLink:
        type: boolean
      points:
        type: integer
      source:
        type: string
    type: object
  res.UserInfoRes:
    properties:
      accountAddress:
        type: string
      email:
        type: string
      username:
        type: string
    type: object
  res.VerifySignatureRes:
    properties:
      token:
        type: string
    type: object
  util.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
info:
  contact: {}
  description: shoe-shark-service API
  title: shoe-shark-service API
  version: "1.0"
paths:
  /api/v1/auth/nonce/{accountAddress}:
    get:
      consumes:
      - application/json
      description: Get Nonce By Account Address
      parameters:
      - description: Wallet Address
        in: path
        name: accountAddress
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.GetNonceRes'
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/util.Response'
            - properties:
                Msg:
                  type: string
              type: object
      summary: Get Nonce
      tags:
      - auth
  /api/v1/auth/nonce/verify:
    post:
      consumes:
      - application/json
      description: Verify the provided signature and return a JWT if valid
      parameters:
      - description: Content to verify
        in: body
        name: content
        required: true
        schema:
          $ref: '#/definitions/req.VerifySignatureReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.VerifySignatureRes'
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/util.Response'
            - properties:
                Msg:
                  type: string
              type: object
      summary: Verify Signature
      tags:
      - auth
  /api/v1/content/{contentId}:
    delete:
      description: Delete a content by ContentID
      parameters:
      - description: Content ID
        in: path
        name: contentId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/util.Response'
            - properties:
                Msg:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/util.Response'
            - properties:
                Msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: Delete a content
      tags:
      - contents
    get:
      description: Get a content by ID
      parameters:
      - description: Content ID
        in: path
        name: contentId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.ContentInfoRes'
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/util.Response'
            - properties:
                Msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: Get a content
      tags:
      - contents
  /api/v1/content/comments:
    post:
      consumes:
      - application/json
      description: 给内容添加评论
      parameters:
      - description: 内容评论结构体
        in: body
        name: content
        required: true
        schema:
          $ref: '#/definitions/req.CreateContentCommentReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/util.Response'
            - properties:
                Msg:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/util.Response'
            - properties:
                Msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 评论内容
      tags:
      - contents
  /api/v1/content/comments/{contentId}:
    get:
      description: 根据内容Id获取评论
      parameters:
      - description: Content ID
        in: path
        name: contentId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.CreateContentCommentRes'
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/util.Response'
            - properties:
                Msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 评论列表
      tags:
      - contents
  /api/v1/content/edit:
    put:
      consumes:
      - application/json
      description: Update a content by ContentID
      parameters:
      - description: Content to update
        in: body
        name: content
        required: true
        schema:
          $ref: '#/definitions/req.UpdateContentReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/util.Response'
            - properties:
                Msg:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/util.Response'
            - properties:
                Msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: Update a content
      tags:
      - contents
  /api/v1/content/list:
    get:
      consumes:
      - application/json
      description: Get a list of contents with pagination and filtering
      parameters:
      - description: Title filter
        in: query
        name: title
        type: string
      - description: Description filter
        in: query
        name: description
        type: string
      - description: Account Address filter
        in: query
        name: account_address
        type: string
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Page size
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/res.ContentInfoRes'
            type: array
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/util.Response'
            - properties:
                Msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: List contents
      tags:
      - contents
  /api/v1/content/save:
    post:
      consumes:
      - application/json
      description: Create a new content
      parameters:
      - description: Content to create
        in: body
        name: content
        required: true
        schema:
          $ref: '#/definitions/req.CreateContentReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/util.Response'
            - properties:
                Msg:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/util.Response'
            - properties:
                Msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: Create a new content
      tags:
      - contents
  /api/v1/contract/nft/mint/white:
    get:
      description: mint nft , this mint must in white list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.ContentInfoRes'
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/util.Response'
            - properties:
                Msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: mint nft
      tags:
      - contract_nft
  /api/v1/oss/upload:
    post:
      consumes:
      - multipart/form-data
      description: 上传图片
      parameters:
      - description: 要上传的图片文件
        in: formData
        name: file
        required: true
        type: file
      produces:
      - text/plain
      responses:
        "200":
          description: 文件上传成功的哈希值
          schema:
            type: string
        "400":
          description: 获取表单错误
          schema:
            type: string
        "500":
          description: 服务器错误
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 上传图片
      tags:
      - 上传
  /api/v1/points/log:
    get:
      consumes:
      - application/json
      description: 查看个人积分记录
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Page size
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/res.PointsLogRes'
            type: array
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/util.Response'
            - properties:
                Msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 查看积分记录
      tags:
      - points
  /api/v1/points/signIn:
    get:
      description: 签到得积分
      produces:
      - application/json
      responses:
        "200":
          description: ok
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/util.Response'
            - properties:
                Msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 签到
      tags:
      - points
  /api/v1/user:
    get:
      consumes:
      - application/json
      description: Get User  By AccountAddress
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.UserInfoRes'
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/util.Response'
            - properties:
                Msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: Get User
      tags:
      - user
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
