basePath: /shoe-shark
definitions:
  req.CreateContentReq:
    properties:
      accountAddress:
        type: string
      body:
        type: string
      isPublic:
        type: boolean
      location:
        type: string
      title:
        type: string
    required:
    - accountAddress
    - body
    - title
    type: object
  req.UpdateContentReq:
    properties:
      accountAddress:
        type: string
      body:
        type: string
      contentId:
        type: string
      isPublic:
        type: boolean
      location:
        type: string
      title:
        type: string
    required:
    - accountAddress
    - body
    - contentId
    - title
    type: object
  req.VerifySignatureReq:
    properties:
      accountAddress:
        type: string
      signature:
        type: string
    required:
    - accountAddress
    - signature
    type: object
  res.ContentInfoRes:
    properties:
      accountAddress:
        type: string
      body:
        type: string
      contentID:
        type: string
      created_at:
        type: string
      isPublic:
        type: boolean
      location:
        type: string
      title:
        type: string
      updated_at:
        type: string
      userID:
        type: string
    type: object
  res.GetNonceRes:
    properties:
      nonce:
        type: string
    type: object
  res.VerifySignatureRes:
    properties:
      token:
        type: string
    type: object
  util.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
info:
  contact: {}
  description: shoe-shark-service API
  title: shoe-shark-service API
  version: "1.0"
paths:
  /api/v1/auth/nonce/{accountAddress}:
    get:
      consumes:
      - application/json
      description: Get Nonce By Account Address
      parameters:
      - description: Wallet Address
        in: path
        name: accountAddress
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.GetNonceRes'
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/util.Response'
            - properties:
                Msg:
                  type: string
              type: object
      summary: Get Nonce
      tags:
      - auth
  /api/v1/auth/nonce/verify:
    post:
      consumes:
      - application/json
      description: Verify the provided signature and return a JWT if valid
      parameters:
      - description: Content to verify
        in: body
        name: content
        required: true
        schema:
          $ref: '#/definitions/req.VerifySignatureReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.VerifySignatureRes'
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/util.Response'
            - properties:
                Msg:
                  type: string
              type: object
      summary: Verify Signature
      tags:
      - auth
  /api/v1/content/{contentId}:
    delete:
      description: Delete a content by ContentID
      parameters:
      - description: schema.Content ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/util.Response'
            - properties:
                Msg:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/util.Response'
            - properties:
                Msg:
                  type: string
              type: object
      summary: Delete a content
      tags:
      - contents
    get:
      description: Get a content by ID
      parameters:
      - description: schema.Content ContentID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.ContentInfoRes'
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/util.Response'
            - properties:
                Msg:
                  type: string
              type: object
      summary: Get a content
      tags:
      - contents
  /api/v1/content/edit:
    put:
      consumes:
      - application/json
      description: Update a content by ContentID
      parameters:
      - description: Content to update
        in: body
        name: content
        required: true
        schema:
          $ref: '#/definitions/req.UpdateContentReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/util.Response'
            - properties:
                Msg:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/util.Response'
            - properties:
                Msg:
                  type: string
              type: object
      summary: Update a content
      tags:
      - contents
  /api/v1/content/save:
    post:
      consumes:
      - application/json
      description: Create a new content
      parameters:
      - description: Content to create
        in: body
        name: content
        required: true
        schema:
          $ref: '#/definitions/req.CreateContentReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/util.Response'
            - properties:
                Msg:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/util.Response'
            - properties:
                Msg:
                  type: string
              type: object
      summary: Create a new content
      tags:
      - contents
  /api/v1/user:
    get:
      consumes:
      - application/json
      description: Get User  By AccountAddress
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/util.Response'
            - properties:
                Msg:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/util.Response'
            - properties:
                Msg:
                  type: string
              type: object
      summary: Get User
      tags:
      - user
swagger: "2.0"
